com.dwarfeng.scg.jdbc.driver=com.mysql.cj.jdbc.Driver
com.dwarfeng.scg.jdbc.url=jdbc:mysql://your-host-here:3306/scg?serverTimezone=Asia/Shanghai&autoReconnect=true
com.dwarfeng.scg.jdbc.username=root
com.dwarfeng.scg.jdbc.password=your-password-here
com.dwarfeng.scg.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
